[pytest]
addopts = -v -s --alluredir=reports/allure-results --reruns 1 -n auto --html=reports/report.html --self-contained-html
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke tests
    sanity: sanity tests
    regression: regression tests
